// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnRoPIQAE6wPDB5xThDjIS0YJ-JaR8FfQ',
    appId: '1:77633190246:web:1babf2b51886c5328db0a7',
    messagingSenderId: '77633190246',
    projectId: 'prescription-app-2d3a7',
    authDomain: 'prescription-app-2d3a7.firebaseapp.com',
    storageBucket: 'prescription-app-2d3a7.appspot.com',
    measurementId: 'G-MTTG70KD9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoPmL19pdcqtLq3gadzFwMyta4NFtgv78',
    appId: '1:77633190246:android:9943f26cd2e8076f8db0a7',
    messagingSenderId: '77633190246',
    projectId: 'prescription-app-2d3a7',
    storageBucket: 'prescription-app-2d3a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXuZ5-56P6sGPhwXrXxMryD0572WceKyg',
    appId: '1:77633190246:ios:e0548f4ee9a07e2e8db0a7',
    messagingSenderId: '77633190246',
    projectId: 'prescription-app-2d3a7',
    storageBucket: 'prescription-app-2d3a7.appspot.com',
    iosBundleId: 'com.example.prescriptionDocument',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXuZ5-56P6sGPhwXrXxMryD0572WceKyg',
    appId: '1:77633190246:ios:b87d8effa379b8948db0a7',
    messagingSenderId: '77633190246',
    projectId: 'prescription-app-2d3a7',
    storageBucket: 'prescription-app-2d3a7.appspot.com',
    iosBundleId: 'com.example.prescriptionDocument.RunnerTests',
  );
}
